apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - flux-resources
################
  - core-services/nginx-ingress
  - core-services/prometheus
################
  - apps/react-app
  - apps/atlantis