grafana:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - grafana.local
    path: /

alertmanager:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - alertmanager.local
    path: /

prometheus:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - prometheus.local
    path: /
