apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '70.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:

    grafana:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - grafana.local
        path: /

    alertmanager:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - alertmanager.local
        path: /

    prometheus:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - prometheus.local
        path: /
