apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: atlantis
spec:
  interval: 5m
  chart:
    spec:
      chart: atlantis
      version: "5.16.0"
      sourceRef:
        kind: HelmRepository
        name: atlantis
        namespace: flux-system
      interval: 1m

  values:

    github:
      user: alizandieh
      token: dammy
      secret: dammy

    orgAllowlist: "*"

    gitconfigSecretName: "atlantis-vcs"
    vcsSecretName: "atlantis-vcs"

    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      host: atlantis.ali-zandieh.com
      path: /
